version: "3.3"
services:

  whoami:
    image: bithavoc/hello-world-env
    container_name: "helloworld-example"
    ports:
      - "3000:3000"
    environment:
      MESSAGE: "\nDev ops and others things"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/helloworld`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      traefik:

networks:
  traefik:
    external: true
